name: dev-ci

on:
  push:
    branches:
      - dev

jobs:
  ci:
    name: Development Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.*

      - name: Restore
        run: dotnet restore V1.sln

      - name: Build
        run: dotnet build V1.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test V1.sln --configuration Release --no-build --verbosity normal